/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unhcrsiteparser;

/**
 *
 * @author ballaz
 */
public class GenerateXML {
    
/**
 * API begins
 * @return 
 */    
private String title, date, id, titleURL, formattedContent, countryCode, news;

static GenerateXML getInstance() {
    return new GenerateXML();
}

void setTitle(String titleText)
{
    title = titleText;
}
void setFormattedContent (String str) {
    formattedContent = str;
}
void setID (String str) {
    id = str;
}
void setDate (String str) {
    date = str;
}
void setURL (String str) {
    titleURL = str;
}
void setCountryCode (String str) {
    countryCode = str;
}
void setNews (String str) {
    news = str;
}

    String getString (String extraline) {
        String str = 
"<item>\n" +
"<title>" +
"" + title + 
"</title>\n" +
"<link>" +
"http://www.unhcr.org/" + countryCode + "/" + id + "-" + titleURL + 
"</link>\n" +
"<pubDate>" + date + " +0000</pubDate>\n" +
"<dc:creator>" +
"<![CDATA[ballaz@unhcr.org]]>" +
"</dc:creator>\n" +
"<guid isPermaLink=\"false\">http://www.unhcr.org/" + countryCode + "/?p=" + id + "</guid>\n" +
"<description></description>\n" +
"<content:encoded>" +
"<![CDATA[" +
"" + formattedContent + 
"]]>" +
"</content:encoded>\n" +
"<excerpt:encoded>" +
"<![CDATA[]]>" +
"</excerpt:encoded>\n" +
"<wp:post_id>" + id + "</wp:post_id>\n" +
"<wp:post_date>" +
"<![CDATA[" + date + "]]>" +
"</wp:post_date>\n" +
"<wp:post_date_gmt>" +
"<![CDATA[" + date + "]]>" +
"</wp:post_date_gmt>\n" +
"<wp:comment_status>" +
"<![CDATA[closed]]>" +
"</wp:comment_status>\n" +
"<wp:ping_status>" +
"<![CDATA[closed]]>" +
"</wp:ping_status>\n" +
"<wp:post_name>" +
"<![CDATA[" +
"" + titleURL + 
"]]>" +
"</wp:post_name>\n" +
"<wp:status>" +
"<![CDATA[publish]]>" +
"</wp:status>\n" +
"<wp:post_parent>0</wp:post_parent>\n" +
"<wp:menu_order>0</wp:menu_order>\n" +
"<wp:post_type>" +
"<![CDATA[" + news + "]]>" +
"</wp:post_type>\n" +
"<wp:post_password>" +
"<![CDATA[]]>" +
"</wp:post_password>\n" +
"<wp:is_sticky>0</wp:is_sticky>\n" +
"<wp:postmeta>" +
"<wp:meta_key>" +
"<![CDATA[_edit_last]]>" +
"</wp:meta_key>\n" +
"<wp:meta_value>" +
"<![CDATA[3]]>" +
"</wp:meta_value>\n" +
"</wp:postmeta>\n" + extraline +
"</item>";
    
    return str;
    }


String beginTheWholeThing() {
    String str = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" +
"<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->\n" +
"<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->\n" +
"<!-- You may use this file to transfer that content from one site to another. -->\n" +
"<!-- This file is not intended to serve as a complete backup of your site. -->\n" +
"\n" +
"<!-- To import this information into a WordPress site follow these steps: -->\n" +
"<!-- 1. Log in to that site as an administrator. -->\n" +
"<!-- 2. Go to Tools: Import in the WordPress admin panel. -->\n" +
"<!-- 3. Install the \"WordPress\" importer from the list. -->\n" +
"<!-- 4. Activate & Run Importer. -->\n" +
"<!-- 5. Upload this file using the form provided on that page. -->\n" +
"<!-- 6. You will first be asked to map the authors in this export file to users -->\n" +
"<!--    on the site. For each author, you may choose to map to an -->\n" +
"<!--    existing user on the site or to create a new user. -->\n" +
"<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->\n" +
"<!--    contained in this file into your site. -->\n" +
"\n" +
"<!-- generator=\"WordPress/4.6.1\" created=\"2016-11-11 09:34\" -->\n" +
"<rss version=\"2.0\"\n" +
"	xmlns:excerpt=\"http://wordpress.org/export/1.2/excerpt/\"\n" +
"	xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n" +
"	xmlns:wfw=\"http://wellformedweb.org/CommentAPI/\"\n" +
"	xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n" +
"	xmlns:wp=\"http://wordpress.org/export/1.2/\"\n" +
">\n" +
"\n" +
"<channel>\n" +
"	<title>Central Europe</title>\n" +
"	<link>http://www.unhcr.org/ceu</link>\n" +
"	<description>UNHCR Regional Site</description>\n" +
"	<pubDate>Fri, 11 Nov 2016 09:34:33 +0000</pubDate>\n" +
"	<language>en-US</language>\n" +
"	<wp:wxr_version>1.2</wp:wxr_version>\n" +
"	<wp:base_site_url>http://www.unhcr.org/</wp:base_site_url>\n" +
"	<wp:base_blog_url>http://www.unhcr.org/ceu</wp:base_blog_url>";

return str;
}

String addBackgroundImageXML (String name, String filename, String url, String title) {
    String str = "<item>\n" +
"		<title>" + title + "</title>\n" +
"		<link>http://www.unhcr.org/" + countryCode + "/" + filename + "</link>\n" +
"		<pubDate>Tue, 01 Nov 2016 12:11:26 +0000</pubDate>\n" +
"		<dc:creator><![CDATA[ballaz@unhcr.org]]></dc:creator>\n" +
"		<guid isPermaLink=\"false\">http://www.unhcr.org/" + countryCode + "/wp-content/uploads/sites/2016/11/" + name + ".jpg</guid>\n" +
"		<description></description>\n" +
"		<content:encoded><![CDATA[]]></content:encoded>\n" +
"		<excerpt:encoded><![CDATA[]]></excerpt:encoded>\n" +
"		<wp:post_id>" + id + "</wp:post_id>\n" +
"		<wp:post_date><![CDATA[2016-11-01 12:11:26]]></wp:post_date>\n" +
"		<wp:post_date_gmt><![CDATA[2016-11-01 12:11:26]]></wp:post_date_gmt>\n" +
"		<wp:comment_status><![CDATA[closed]]></wp:comment_status>\n" +
"		<wp:ping_status><![CDATA[closed]]></wp:ping_status>\n" +
"		<wp:post_name><![CDATA[" + title + "]]></wp:post_name>\n" +
"		<wp:status><![CDATA[inherit]]></wp:status>\n" +
"		<wp:post_parent>0</wp:post_parent>\n" +
"		<wp:menu_order>0</wp:menu_order>\n" +
"		<wp:post_type><![CDATA[attachment]]></wp:post_type>\n" +
"		<wp:post_password><![CDATA[]]></wp:post_password>\n" +
"		<wp:is_sticky>0</wp:is_sticky>\n" +
"		<wp:attachment_url><![CDATA[" + url + "]]></wp:attachment_url>\n" +
"		<wp:postmeta>\n" +
"			<wp:meta_key><![CDATA[_wp_attached_file]]></wp:meta_key>\n" +
"			<wp:meta_value><![CDATA[2016/11/" + filename + "]]></wp:meta_value>\n" +
"		</wp:postmeta>\n" +
"		<wp:postmeta>\n" +
"			<wp:meta_key><![CDATA[_wp_attachment_metadata]]></wp:meta_key>\n" +
"			<wp:meta_value></wp:meta_value>\n" +
"		</wp:postmeta>\n" +
"	</item>";
    return str;
}

    private GenerateXML () {
        
        
    }
    
    
}
